hoosactive/urls.py
from django.urls import path

from . import views


app_name = 'hoosactive'

urlpatterns = [

    path('', views.index, name='index'),
    path('log-exercise/<str:redir>/', views.log_exercise, name='log_exercise'),
    path('schedule-workout/<str:redir>/', views.schedule_workout, name='schedule_workout'),
    path('login/', views.login, name='login'),
    path('profile/', views.profile_noname, name='profile_noname'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/create/', views.create, name='create'),
    path('profile/<str:username>/update/', views.create, name='update'),
    path('profile/<str:username>/friends/', views.friends, name='friends'),
    path('profile/<str:username>/friends/<str:error>/', views.friends_error, name='friends_error'),
    path('profile/<str:username>/send-request/<str:user2>/', views.send_request, name='send_request'),
    path('profile/<str:username>/remove-friend/<str:user2>/', views.remove_friend, name='remove_friend'),
    path('profile/<str:username>/request-respond/<str:user2>/<str:action>/', views.request_response, name='request_response'),
    path('register/', views.register, name="register"),
    path('leaderboard/', views.leaderboard, name="leaderboard"),
    path('leaderboard/<str:exercise_name>/<str:sort>/<str:timeframe>/<str:population>/', views.exercise_leaderboard, name="exercise_leaderboard"),
    path('search/', views.search, name='search'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('password/reset/', views.password_reset, name='password_reset'),
    path('password/change/<uidb64>/<token>', views.password_change, name='password_change'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('hoosactive.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoosactive/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import SetPasswordForm, UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User
from django import forms
from hoosactive.models import Profile

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class PostForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['age', 'height_feet', 'height_inches', 'weight_lbs', 'bio_text', 'city', 'state', 'show_stats', 'receive_notifications']

class ChangePictureForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['profile_pic']

class UserPasswordResetForm(SetPasswordForm):
    new_password1 = forms.CharField(label='Password',
        help_text="<ul class='errorlist text-muted'><li>Your password can 't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can 't be a commonly used password.</li> <li>Your password can 't be entirely numeric.<li></ul>",
        max_length=100,
        required=True,
        widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password',
            'type': 'password',
            'id': 'user_password',
        }))

    new_password2 = forms.CharField(label='Confirm password',
        help_text=False,
        max_length=100,
        required=True,
        widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'confirm password',
            'type': 'password',
            'id': 'user_password',
        }))


class UserForgotPasswordForm(PasswordResetForm):
    email = forms.EmailField(label='Email address',
        max_length=254,
        required=True,
        widget=forms.TextInput(
         attrs={'class': 'form-control',
                'placeholder': 'email address',
                'type': 'text',
                'id': 'email_address'
                }
        ))

hoosactive/views.py
from django.db.models import Sum, Avg, Func
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.utils import timezone

from django.core.mail import send_mail
from mysite.settings import EMAIL_HOST_USER
from .tokens import account_activation_token, password_reset_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.views import generic
from django.template import loader

from django.contrib import messages
from django.contrib.auth import authenticate, update_session_auth_hash
from django.contrib.auth import login as auth_login

from .forms import CreateUserForm, PostForm, ChangePictureForm, UserForgotPasswordForm, UserPasswordResetForm
from .models import *

import datetime

def index(request):
    user = request.user
    try:
        user.profile
    except:
        recent_entries = []
        workout_list = []
        count = 0
    else:
        recent_entries = user.profile.get_recent_entries()
        workout_list = user.profile.get_upcoming_workouts()
        count = workout_list.count()
    return render(request, 'hoosactive/index.html', {
        'exercise_list': Exercise.objects.order_by('name'),
        'recent_entries': recent_entries,
        'redirect': 'index',
        'workout_blank': range(0,5-count),
        'workout_list': workout_list
    })

def log_exercise(request, redir):
    user = request.user
    if (user.is_authenticated):
        try:
            user.profile
        except:
            return HttpResponseRedirect('/profile/'+user.username+'/create/')
        else:
            if request.method == 'POST':
                exer = Exercise.objects.get(name=request.POST['drop'])
                user.profile.add_exercise(exer.name)

                # calories_burned min/max
                calories_burned = max(0, int(request.POST['calories_burned']))
                calories_burned = min(9999, calories_burned)

                # duration min/max
                duration = max(0.00, round(float(request.POST['duration']),2))
                duration = min(99.99, duration)

                # extra data
                extra_data = max(0.00, round(float(request.POST['extra']),2))
                extra_data = min(99.99, extra_data)

                entry = Entry.objects.create_entry(user,user.username,user.profile.city,exer,request.POST['date'],calories_burned,duration,extra_data)
                return redirect('hoosactive:'+redir)
    else:
        return redirect('hoosactive:login')

def schedule_workout(request, redir):
    user = request.user
    if (user.is_authenticated):
        if request.method == 'POST':
            workout = Workout.objects.schedule_workout(user,request.POST['description'],request.POST['date'])
            return redirect('hoosactive:'+redir)
    else:
        return redirect('hoosactive:login')

def register(request):
    if request.user.is_authenticated:
        return redirect('hoosactive:index')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                # Check if email has already been registered
                check_email = request.POST.get('email')
                check_user = User.objects.filter(email=check_email)
                if len( check_user ) > 0:
                    messages.add_message(request, messages.WARNING, 'This email or username has already been registered to another user')
                    return render(request, 'hoosactive/register.html',{
                        'form': form,
                        'redirect': 'index',
                    })

                user = form.save()
                user.is_active = False
                user.save()
                username = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + username + '. We sent you an email to activate your account')
                # Send activation email
                url = request.META['HTTP_HOST'] + '/activate/' + urlsafe_base64_encode(force_bytes(user.pk)) + '/' + account_activation_token.make_token(user)
                mes = ( 'Activate your email by clicking the following link:\n' +
                       url
                )
                send_mail( 'Activate Email for HoosActive!', mes, EMAIL_HOST_USER, [user.email] )

                return redirect('hoosactive:login')

        return render(request, 'hoosactive/register.html', {
            'form': form,
            'redirect': 'index',
        })

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
        messages.add_message(request, messages.WARNING, str(e))
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # Send Welcome Email
        subj = "Welcome to HoosActive!"
        message = ( "Hey " + user.username + "!" +
                  "\n\nWelcome to the fastest growing health and fitness platform in Charlottesville! " +
                  "We look forward to seeing the progress you make toward achieving your goals! " +
                  "\n\nHappy Workouts!\nThe HoosActive Team" )
        send_mail( subj, message, EMAIL_HOST_USER, [user.email] )
    else:
        messages.add_message(request, messages.WARNING, 'Account activation link is invalid.')

    return redirect('hoosactive:index')

#https://www.youtube.com/watch?v=tUqUdu0Sjyc used the following toutrial for login and parts of registration
def login(request):
    if request.user.is_authenticated:
        return redirect('hoosactive:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None and user.is_active is not False:
                auth_login(request, user)
                return redirect('hoosactive:index')
            else:
                messages.info(request, 'Username OR password is incorrect, make sure your email is activated')

        return render(request, 'hoosactive/login.html', {
            'redirect': 'index',
        })

def profile_noname(request):
    return HttpResponseRedirect('/profile/'+request.user.username)

def profile(request, username):
    authenticated_user = request.user
    profile_user = User.objects.get(username=username)

    if authenticated_user.is_authenticated:
        try:
            profile_user.profile
        except:
            if (authenticated_user == profile_user):
                return HttpResponseRedirect('/profile/'+request.user.username+'/create/')
            else:
                return redirect('hoosactive:index')
        else:
            picture_form = ChangePictureForm(instance=profile_user.profile)
            if request.method == 'POST':
                picture_form = ChangePictureForm(request.POST, request.FILES, instance=profile_user.profile)
                if picture_form.is_valid():
                    picture_form.save()

            stat_dict = {}
            max_cals = 0
            cals_burned = 0

            for i in range(0,7):
                date = timezone.now()-datetime.timedelta(days=6-i)
                day_of_week = date.strftime('%a')
                dm_format = date.strftime('%m') + '/' + date.strftime('%d')

                aggregate = Entry.objects.filter(
                    user=profile_user.id
                ).filter(
                    date__day=date.day
                ).filter(
                    date__month=date.month
                ).filter(
                    date__year=date.year
                ).values(
                    'username',
                ).annotate(
                    total_cals=Sum('calories'),
                )

                if (aggregate.count() != 0):
                    cals_burned = int(aggregate[0]['total_cals'])
                    stat_dict[day_of_week] = (cals_burned, dm_format)
                    max_cals = max(cals_burned, max_cals)
                else:
                    stat_dict[day_of_week] = (0, dm_format)

            workout_list = profile_user.profile.get_upcoming_workouts()

            return render(request, 'hoosactive/profile.html', {
                'exercise_list': Exercise.objects.order_by('name'),
                'is_friend': authenticated_user.profile.is_friends_with(profile_user),
                'is_requested': profile_user.profile.requested_by(authenticated_user),
                'max_cals': max_cals,
                'picture_form': picture_form,
                'profile_user': profile_user,
                'recent_entries': authenticated_user.profile.get_recent_entries(),
                'redirect': 'profile_noname',
                'workout_blank': range(0,5-workout_list.count()),
                'workout_list': workout_list,
                'show_stats': profile_user.profile.show_stats,
                'stat_dict': stat_dict
            })
    else:
        return redirect('hoosactive:login')

def friends(request, username):
    return HttpResponseRedirect("/profile/"+username+"/friends/all/")

def friends_error(request, username, error):
    authenticated_user = request.user
    profile_user = User.objects.get(username=username)

    error_message = False
    if error == "nouserfound":
        error_message = True

    if authenticated_user.is_authenticated:
        try:
            profile_user.profile
        except:
            if (authenticated_user == profile_user):
                return HttpResponseRedirect('/profile/'+request.user.username+'/create/')

hoosactive/templates/hoosactive/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  {% load i18n %}
  <link rel="shortcut icon" type="image/png" href="{% static 'hoosactive/images/ha.png' %}"/>
  <title>HoosActive</title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Bootstap icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'hoosactive/style.css' %}">
  <!-- Custom JS -->
  <script src="{% static 'hoosactive/script.js' %}"></script>
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Google Charts -->
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>

<nav class="b12-navbar">
  <a style="width: 200px;" href="{% url 'hoosactive:index' %}">
    <div style="display: flex; align-items: center; justify-content: center;">
      <img style="max-width: 100%; max-height: 80px;" src="{% static 'hoosactive/images/hoosactive_logo.png' %}" alt="">
    </div>
  </a>
  <div class="b12-navbar-links">
    {% if user.is_authenticated %}
    <a class="b12-nav-item" href="{% url 'hoosactive:profile' user.username %}">
      <div><div>Profile</div></div>
    </a><a class="b12-nav-item" href="{% url 'hoosactive:leaderboard' %}">
      <div><div>Leaderboard</div></div>
    </a>
    <!-- Sign Out with Modal confirmation. -->
    <button id="SignOutNavBtn" class="b12-nav-item" style="background-color: transparent; border-color: transparent;" class="btn btn-primary" data-toggle="modal" data-target="#SignOutModal">Sign Out</button>
    {% else %}
    <div class="b12-nav-item blank"></div>
    <div class="b12-nav-item blank"></div>
    <a class="b12-nav-item" href="{% url 'hoosactive:login' %}"><div>Register/Sign In</div></a>
    {% endif %}
  </div>
</nav>

{% block content %}{% endblock %}

<!-- Sign Out Modal -->
<div id="SignOutModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-dark text-left">Are you sure you want to sign out?</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="{% url 'account_logout' %}">
          {% csrf_token %}
          <button class="btn btn-primary">{% trans 'Sign Out' %}</button>
        </form>
      </div>
    </div>
  </div>
</div>

<footer></footer>
<!-- Bootstrap popper.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

hoosactive/templates/hoosactive/login.html
{% extends "hoosactive/base.html" %}
{% block content %}
{% load static %}

{% load socialaccount %}

<body>
	<div class="container h-100 mt-3">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
          <h2 class="mt-1" style="color: #FFF; text-align: center; margin-bottom: 0 !important; font-size: 20px;">LOGIN</h2>
				</div>
				<div class="d-flex justify-content-center" style="margin-top: 20px;">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
              <input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>
						<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   	</div>
					</form>
				</div>

				<div class="mt-3">
					<div class="d-flex justify-content-center" style="color: white;">
						Don't have an account? <a href="{% url 'hoosactive:register' %}" class="ml-2" style="text-decoration: none;">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center" style="color: white;">
						Forgot Your Password? <a href="{% url 'hoosactive:password_reset' %}" class="ml-2" style="text-decoration: none;">Reset Password</a>
					</div>
          {% for message in messages %}
          <div class="message mt-1">
            {{message}}
          </div>
  				{% endfor %}
        </div>
			</div>
		</div>
    <hr width="350px" color="black" style="margin-bottom: 16px">
    <div class="d-flex justify-content-center">
      <a class="btn btn-outline-dark" href="{% provider_login_url 'google' %}" role="button" style="text-transform:none">
        <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
        Login with Google
      </a>
    </div>

	</div>

  <script>

    // Because I didn't set placeholder values in forms.py,
    // they will be set here using vanilla Javascript.
    // We start indexing at one because CSRF_token
    // is considered an input field.

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username...';
    form_fields[2].placeholder='Password...';

    for (var field in form_fields){
      form_fields[field].className += ' form-control'
    }

  </script>
</body>

{% endblock %}

hoosactive/templates/hoosactive/profile.html
{% extends "hoosactive/base.html" %}
{% block content %}
{% load static %}
<body style="background-color: #EEEEEE;">
  <div style="height: 100%; text-align: center;">
    {% if user.is_authenticated %}
    <div class="profile-col-container no-gutters">
      <div id="col1" class="mt-5 profile-col-flip">

        <!-- This is a chart. -->
        <div style="width: 100%;">
          <div style="width: 500px; margin: auto;">
            <text style="font-size: 24px;">Calories Burned Per Day</text>
            <div class="profile-chart-row" style="height: 224px; align-items: flex-end;">
              {% for day, cals in stat_dict.items %}
              <div style="width: calc(100%/7); height: calc(200px*{{ cals.0 }}/{{ max_cals }} + 24px); padding: 0 0.3%;">
                <text>{{ cals.0 }}</text>
                <div class="profile-chart-bar" style="background: #007BFFC5; width: 100%; height: calc(200px*{{ cals.0 }}/{{ max_cals }});"></div>
              </div>
              {% endfor %}
            </div>
            <hr style="margin: 0; height: 1px; background: black;">
            <div class="profile-chart-row" style="align-items: flex-start;">
              {% for day, cals in stat_dict.items %}
              <text style="width: calc(100%/7); padding: 0 0.3%;">{{ day }}</text>
              {% endfor %}
            </div>
            <div class="profile-chart-row" style="align-items: flex-start;">
              {% for day, cals in stat_dict.items %}
              <text style="width: calc(100%/7); padding: 0 0.3%;">{{ cals.1 }}</text>
              {% endfor %}
            </div>
          </div>
        </div>

        {% if user == profile_user %}
        <!-- Button meant to open Modal to adding exercise. -->
        <button style="font-size: 25px;" class="bi bi-plus-circle col-8 mt-5 mx-5 p-3 btn btn-outline-primary font-weight-bold" data-toggle="modal" data-target="#AddExerciseModal"> ADD EXERCISE </button>
        <!-- Modal in base.html -->

        <!-- Button meant to direct to workout scheduler. -->
        <button style="font-size: 25px;" class="bi bi-calendar-date col-8 mt-4 mx-5 mb-3 p-3 btn btn-outline-primary font-weight-bold" data-toggle="modal" data-target="#ScheduleWorkoutModal"> SCHEDULE WORKOUT </button>
        <!-- Modal in base.html -->
        {% endif %}

      </div>

      <div id="col2" class="mt-5 profile-col-flip">
        <div class="mx-auto" style="border-radius: 50%; width: 200px; height: 200px; overflow: hidden;">
          <img src="{{profile_user.profile.profile_pic.url}}" width=200>
        </div>

        {% if profile_user.first_name %}
        <p class="font-weight-bold" style="font-size:30px;color:rgb(72,72,72);">{{ profile_user.first_name }} {{ profile_user.last_name }}</p>
        {% else %}
        <p class="font-weight-bold" style="font-size:30px;color:rgb(72,72,72);">{{ profile_user.username }}</p>
        {% endif %}

        <p class="px-5" style="font-size:20px;color:black;">{{ profile_user.profile.bio_text }}</p>
        {% if show_stats %}
        <p style="font-size:20px;color:black;">{{ profile_user.profile.age }}  -  {{ profile_user.profile.height_feet }}'{{ profile_user.profile.height_inches }}"  -  {{ profile_user.profile.weight_lbs }} lbs</p>
        {% endif %}
        <p style="font-size:20px;color:black;">{{ profile_user.profile.city }}, {{ profile_user.profile.state }}</p>

        <a href="/profile/{{ profile_user.username }}/friends/"><button class="col-5 mt-2 mx-5 p-3 btn btn-outline-primary font-weight-bold">Friends</button></a>
        <br>
        {% if user == profile_user %}

        <!-- <a href="/profile/{{ user.username }}/update/"> -->
        <button class="col-5 mt-2 mx-5 p-3 btn btn-outline-primary font-weight-bold" data-toggle="modal" data-target="#SettingsModal">Settings</button>
        <!-- </a> -->

        {% else %}
        {% if is_friend %}
        <a href="/profile/{{ user.username }}/remove-friend/{{ profile_user.username }}/"><button class="col-5 mt-2 mx-5 p-3 btn btn-outline-primary font-weight-bold">Remove Friend</button></a>
        {% else %}
        {% if is_requested %}
        <button class="col-5 mt-2 mx-5 p-3 btn btn-outline-secondary font-weight-bold" disabled>Request Sent</button>
        {% else %}
        <a href="/profile/{{ user.username }}/send-request/{{ profile_user.username }}/"><button class="col-5 mt-2 mx-5 p-3 btn btn-outline-primary font-weight-bold">Send Friend Request</button></a>
        {% endif %}
        {% endif %}
        {% endif %}
      </div>
    </div>

    {% endif %}
  </div>

  <div style="padding: 0 50px; margin-top: 50px;">

  <!-- Settings Modal -->
  <div id="SettingsModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Settings</h5>
        </div>
        <div class="modal-body">
          <h1 class="font-weight-bold" style="text-align: center; font-size: 18px;">Change Profile Photo</h1>
          <div style="text-align: center;" class="mb-3">
            <form method="POST" action="" enctype="multipart/form-data">
              {% csrf_token %}
              {{picture_form.profile_pic}}
              <input class="btn btn-primary" type="submit" name="Update Information" value="Update">
            </form>
          </div>
          <a href="/profile/{{ user.username }}/update/">
            <button style="width: 100%; font-size: 18px;" class="mb-1 p-3 btn btn-outline-primary font-weight-bold">Edit Profile Information</button>
          </a>
          <br></br>
          <a href="{% url 'hoosactive:password_reset' %}">
            <button style="width: 100%; font-size: 18px;" class="mb-3 p-3 btn btn-outline-primary font-weight-bold">Change Password</button>
          </a>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<!-- Add Exercise Modal -->
<div id="AddExerciseModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Exercise</h5>
      </div>
      <div class="modal-body">
        <form action="{% url 'hoosactive:log_exercise' redirect %}" method="post">
          {% csrf_token %}
          <select id="drop" name="drop" class="form-control" onchange="updateEntryModal()" required>
            <option value="" selected disabled>Select Exercise Type</option>
            {% for exercise in exercise_list %}
            <option value="{{ exercise.name }}" data-type="{{ exercise.type }}">{{ exercise.name }}</option>
            {% endfor %}
            <option value="" disabled>Recent Entries</option>
            {% for entry in recent_entries %}
            <option value="{{ entry.exercise.name }}" data-duration="{{ entry.duration_hours }}" data-calories="{{ entry.calories }}" data-type="{{ entry.exercise.type }}" data-extra="{{ entry.extra }}">{{ entry.exercise }} on {{ entry.date }}</option>
            {% endfor %}
          </select>
          <label for="date">Timestamp</label>
          <input class="my-2 form-control" type="datetime-local" name="date" id="date" required>
          <label for="duration">Duration (hrs)</label>
          <input class="my-2 form-control" type="number" placeholder="0.00" name="duration" id="duration" step="0.01" required>
          <label for="calories_burned">Calories Burned</label>
          <input class="my-2 form-control" type="number" placeholder="0000" name="calories_burned" id="calories_burned" required>
          <div id="insertExtra"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <input type="submit" class="btn btn-primary" value="Log Exercise">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Schedule Workout Modal -->
<div id="ScheduleWorkoutModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Schedule Workout</h5>
      </div>
      <div class="modal-body">
        <form action="{% url 'hoosactive:schedule_workout' redirect %}" method="post">
          {% csrf_token %}
          <label for="description">Workout Name</label>
          <input class="my-2 form-control" placeholder='e.g. "1-Mile Run"' name="description" id="description" required>
          <label for="date">Timestamp</label>
          <input class="my-2 form-control" type="datetime-local" name="date" id="date" required>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <input type="submit" class="btn btn-primary" value="Schedule">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}